name: enduromtb
favicon: null
layout_spectrum: 0.75259
typography_spectrum: 0.06895892531611025
title: Enduro Mountain Biking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6452605822123587
  lightness: 0.28293321235105395
  saturation: 0.9059287768322974
  rhythmicContrast: 0.8221788234077394
purpose: []
