name: enduromtb
favicon: null
layout_spectrum: 0.75259
typography_spectrum: 0.18826
title: Enduro Mountain Biking
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
    - '#000000'
  brandStrength: 0.8125
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
